name:                latte
version:             0.1.0.0
github:              "radrow/latte"
license:             BSD3
author:              "Radosław Rowicki"
maintainer:          "rr386088@students.mimuw.edu.pl"
copyright:           "2019 Radosław Rowicki"

extra-source-files:
- README.org

description:         A compiler for the Latte programming language

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - DataKinds
    - MultiWayIf
    - KindSignatures
    - TypeOperators
    - FlexibleInstances
    - FunctionalDependencies
    - MultiParamTypeClasses
  dependencies:
    - mtl
    - lens
    - ghc-prim
    - megaparsec
    - parser-combinators
    - text
    - containers
    - ghc
    - pretty
    - hashtables
    - file-embed
    - bytestring
    - directory
    - filepath
    - array

executables:
  lattec:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wno-implicit-prelude
    dependencies:
    - latte
    - filepath
    - process
    - text
